# Generated by Django 2.0.4 on 2018-06-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='町名')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='事件名')),
                ('time', models.CharField(max_length=127, verbose_name='発生時刻')),
                ('content', models.TextField(blank=True, verbose_name='事件内容')),
            ],
        ),
    ]
